image: debian:jessie

before_script:
  - scripts/bootstrap.sh

stages:
  - check
  - provision
  - test

check:
  stage: check
  script:
    - make check

provision:
  stage: provision
  script:
    - scripts/apply.sh

test:
  stage: test
  script:
    - test.sh
