image: debian:jessie

before_script:
  # provision requirements
  - scripts/bootstrap.sh

stages:
  - check
  - provision
  - test

check:
  stage: check
  before_script:
    # install check requirements
    - apt-get update -yqq
    - apt-get install -yqq make puppet-lint shellcheck
  script:
    - make check

provision:
  stage: provision
  script:
    - scripts/apply.sh

test:
  stage: test
  script:
    - test.sh
