image: debian:jessie

before_script:
  # install provision dependencies
  - apt-get update -yqq
  - apt-get install -yqq make ruby git
  - gem install librarian-puppet
  # bootstrap provisioning
  - scripts/bootstrap.sh

stages:
  - check
  - provision
  - test

check:
  stage: check
  before_script:
    # install check requirements
    - apt-get update -yqq
    - apt-get install -yqq make puppet-lint shellcheck
  script:
    - make check

provision:
  stage: provision
  script:
    # provision with puppet
    - scripts/apply.sh
  artifacts:
    paths:
      - Puppetfile.lock

test:
  stage: test
  script:
    - test.sh
