image: debian:jessie

variables:
  FACTER_env: gitlab
  FACTER_fqdn: faalserver.faalkaart.dev

before_script:
  # install provision dependencies
  - apt-get update -yqq
  - apt-get install -yqq make ruby git netcat
  - gem install librarian-puppet
  # bootstrap provisioning
  - scripts/bootstrap.sh
  - make Puppetfile.lock

stages:
  - check
  - provision

check:
  stage: check
  before_script:
    # install check requirements
    - apt-get update -yqq
    - apt-get install -yqq make puppet-lint shellcheck
  script:
    - make check

provision:
  stage: provision
  script:
    # provision with puppet
    - scripts/apply.sh
    # test
    - scripts/test.sh
    # save content for artifact
    - curl -sSk https://localhost -H host:faalkaart.nl > index.html
    - curl -sSkI https://localhost -H host:faalkaart.nl > response.txt
  artifacts:
    paths:
      - Puppetfile.lock
      - index.html
      - response.txt
