image: debian:jessie

before_script:
  - scripts/bootstrap.sh

stages:
<<<<<<< HEAD
  - check
  - provision
  - test

check:
  stage: check
  script:
    - make check

provision:
  stage: provision
  script:
    - scripts/apply.sh

test:
  stage: test
  script:
    - test.sh
=======
  - provision
  - test

provision:
  stage: provision
  script:
    scripts/apply.sh

test:
  stage: test
  script: test.sh
>>>>>>> gitlab/master
